title: Resume
author: Ness Reliford
email: noway@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a blockchain developer who specialzes in gaming apps. My passion is what drives me, see what I've been working on:
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
